<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    function search($repo, $word){
        $query = $repo->createQueryBuilder('p')
            ->where('p.title LIKE :title')
            ->setParameter('title', '%'.$word->getName().'%')
            ->getQuery()->getResult();

        return $query;
    }
}
