<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    function search($repo, $word){
        $query = $repo->createQueryBuilder('p')
            ->where('p.title LIKE :title')
            ->setParameter('title', '%'.$word->getName().'%')
            ->getQuery()->getResult();

        return $query;
    }

    function lastNews($repositories){
        $query = $repositories->createQueryBuilder('p')
            ->orderBy('p.createTime', 'DESC')
            ->setMaxResults(3)
            ->getQuery()->getResult();

        return $query;
    }

    function popularNews($repositories){
        $query = $repositories->createQueryBuilder('p')
            ->orderBy('p.rating', 'DESC')
            ->setMaxResults(5)
            ->getQuery()->getResult();

        return $query;
    }
}
